- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-scylla-bench/operation/counter_update.rs
- src/bin/cql-stress-scylla-bench/operation/read.rs
- src/bin/cql-stress-scylla-bench/operation/scan.rs
- src/bin/cql-stress-scylla-bench/operation/write.rs
Currently, driver-side timeouts are implemented manually using `tokio::time::timeout`. The newest version of the scylla-rust-driver, `0.5.0`, supports driver-side timeouts through its API. This PR updates the rust driver version and then removes the old, hacky way of enforcing timeouts, replacing it with the kosher one.
> s-b: driver-side timeouts

- src/bin/cql-stress-scylla-bench/main.rs
This PR does two things:
- Changes the default verbosity level from "error" to "warn",
- Adds a warning about running in debug mode (so that users don't accidentally benchmark with a debug version).
> s-b: improvements to logging

- src/bin/cql-stress-scylla-bench/gocompat/strconv.rs
- src/bin/cql-stress-scylla-bench/main.rs
- src/run.rs
The `bool::then_some` function got stabilized, and clippy started complaining about the usage of `bool::then` with lambdas that immediately return a value. This commit switches uses of `then` to `then_some` where applicable.
> treewide: appease clippy

- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-scylla-bench/args.rs
- src/bin/cql-stress-scylla-bench/histogram_log_writer.rs
- src/bin/cql-stress-scylla-bench/main.rs
- src/bin/cql-stress-scylla-bench/operation/counter_update.rs
- src/bin/cql-stress-scylla-bench/operation/read.rs
- src/bin/cql-stress-scylla-bench/operation/scan.rs
- src/bin/cql-stress-scylla-bench/operation/write.rs
- src/bin/cql-stress-scylla-bench/stats.rs
- src/configuration.rs
- src/run.rs
This PR add support for the following scylla-bench options related to latency histograms:
- `-latency-type` - determines which type of latency should be printed to the standard output (raw or coordinated-omission fixed),
- `-measure-latency` - controls whether latency should be measured at all,
- `-hdr-latency-sig` - controls the precision of the latency histograms (significant figures),
- `-hdr-latency-units` - determines the units used to record the latency,
- `-hdr-latency-file` - name of the file to which latency information should be saved, in the HistogramLogWriter format. Results can be viewed using e.g. the following page: https://hdrhistogram.github.io/HdrHistogramJSDemo/logparser.html
> Add histogram-related options

- Cargo.lock
- Cargo.toml
- src/run.rs
Currently, the loop in `WorkerContext::run_worker` doesn't allow the worker to quit in case the operation it tries to perform constantly fails. This commit modifies the logic so that it will stop when asked, even if it got stuck on an error.
> run: make it possible to stop runs that constantly fail

- src/bin/cql-stress-scylla-bench/operation/counter_update.rs
- src/bin/cql-stress-scylla-bench/operation/read.rs
- src/bin/cql-stress-scylla-bench/operation/scan.rs
- src/bin/cql-stress-scylla-bench/operation/write.rs
- src/configuration.rs
- src/run.rs
Currently, Rust does not support async in traits natively and usually
the "async-trait" crate is used to make async methods work. The main
limitation of async-trait is that it requires boxing the future returned
from the async function - so, an allocation.
The `Operation::execute` method is async, so it incurs an allocation for
each operation executed in the benchmark. While the driver itself
performs multiple allocations when handling a single request, for some
reason the allocation related to boxing the future was prominent in
flamegraphs of CPU-bound workloads (it took about 10% of the time).
This commit refactors the Operation so that it is responsible for
running its own `execute` loop in `Operation::run`. In order to make
migration to the new pattern easy, a macro `make_runnable!` …
> run: get rid of a per-operation allocation 

- src/bin/cql-stress-scylla-bench/gocompat/strconv.rs
- src/bin/cql-stress-scylla-bench/workload/sequential.rs
- src/bin/cql-stress-scylla-bench/workload/timeseries_write.rs
With the new clippy version comes new lints. This commit fixes the newest complaints so that the CI passes again.
> treewide: fix clippy's complaints

- src/distribution.rs
Clippy complained about:
https://rust-lang.github.io/rust-clippy/master/index.html#/manual_next_back. This commit fixes this issue.
> s-b: clippy fixes

- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/settings/command/help.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/read_write.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/parser.rs
- src/bin/cql-stress-cassandra-stress/settings/param/simple_param.rs
- src/bin/cql-stress-cassandra-stress/settings/test.rs
cassandra-stress accepts the CLI arguments of the following form:
`./cassandra-stress COMMAND [command_params...] [OPTION [option_params...] ...]`
An example:
`./cassandra-stress read cl=QUORUM n=10000 -schema replication(factor=1) -mode cql3 native -rate threads=10`
In this case the command is `read` and its parameters are `cl=` and `n=`.
Apart from the command, there are three options:
* -schema with `replication` parameter
* -mode with `cql3` and `native` parameters
* -rate with a single `threads=` parameter
Introduced corresponding modules:
* `settings` - Entry for CLI arguments parsing.
* `settings::param` - Contains the parameter abstraction and exposes parameters' parser API to the users (see `settings::command`).
* `settings::command` - Parses command and its parameters
Currently, …
> c-s: basic CLI arguments parser

- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-scylla-bench/main.rs
As stated in the first commit message, some [tracing](https://docs.rs/tracing/latest/tracing/) logs were not consumed (not displayed).
To be more precise: all logs emitted after the first `await` were simply ignored.
A simple example (before the changes). Adding two simple logs in
`src/bin/cql-stress-scylla-bench/main.rs::prepare`:
```rust
tracing::info!("Before build");
let session = builder.build().await?;
tracing::info!("After build");
```
Now, looking at the output of some simple command:
```
$ RUST_LOG=info cargo run --release --bin cql-stress-scylla-bench -- -mode write -workload sequential -nodes "172.17.0.2:9042" --partition-count 100000
Finished release [optimized] target(s) in 0.03s
Running `target/release/cql-stress-scylla-bench -mode write -workload sequential -nodes …
```
> cql-stress tracing: replace `env_logger` with `tracing-subscriber`

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/settings/command/read_write.rs
- src/bin/cql-stress-cassandra-stress/settings/param/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/parser.rs
- src/bin/cql-stress-cassandra-stress/settings/param/simple_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
Before the changes, the parser would only validate the input, returning the validated string to the user (which still needs to be parsed to the according type).
This PR introduces the changes that address this issue. The major change is the introduction of `Parsable` trait described in the code. The `SimpleParam` is now generic over `Parsable` trait.
Most of the changes include adjusting the rest of the code to `Parsable` trait + some fixups.
- Introduced `Parsable` trait
- Made `SimpleParam` be generic over `Parsable`
- Adjusted the rest of the code to usage of generic `SimpleParam`
- some fixups, such as changing the types of `duration`, or `consistency_level` parameters
> c-s: parser refactor

- src/bin/cql-stress-cassandra-stress/settings/command/help.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/read_write.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/node.rs
- src/bin/cql-stress-cassandra-stress/settings/option/rate.rs
- src/bin/cql-stress-cassandra-stress/settings/option/schema.rs
- src/bin/cql-stress-cassandra-stress/settings/param/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/multi_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/parser.rs
- src/bin/cql-stress-cassandra-stress/settings/param/simple_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
Introduced modules:
* settings::option - Parses options and its parameters
Supported options:
-node
-schema
-rate
These options should be enough for implementing the runtime.
Apart from that - extended parameters' parsing module by introducing `MultiParam`. A multiparameter is a complex parameter that contains subparameters. For example, given the output of `./cassandra-stress help -schema`:
```
Usage: -schema [replication(?)] [keyspace=?] [compaction(?)] [compression=?]
replication([strategy=?][factor=?][<option 1..N>=?]): Define the replication strategy and any parameters
strategy=? (default=org.apache.cassandra.locator.SimpleStrategy) The replication strategy to use
factor=? (default=1)                     The number of replicas
keyspace=? (default=keyspace1)           The keyspace …
```
> c-s CLI: Options parsing

- src/bin/cql-stress-cassandra-stress/settings/test.rs
- src/bin/cql-stress-scylla-bench/operation/mod.rs
The version of clippy just got bumped, and so new lints were introduced. This PR fixes the failing checks for cql-stress.
- replaced unnecessary `vec!` with an array in the test
- removed unnecessary `pub(self)` identifiers in s-b operation module
> treewide: clippy fixes

- src/bin/cql-stress-cassandra-stress/java_generate/values/blob.rs
- src/bin/cql-stress-cassandra-stress/java_generate/values/hex_blob.rs
- src/bin/cql-stress-cassandra-stress/java_generate/values/mod.rs
- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/operation/mod.rs
- src/bin/cql-stress-cassandra-stress/operation/read.rs
- src/bin/cql-stress-cassandra-stress/operation/row_generator.rs
- src/bin/cql-stress-cassandra-stress/operation/write.rs
- src/bin/cql-stress-cassandra-stress/settings/command/help.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/read_write.rs
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/node.rs
- src/bin/cql-stress-cassandra-stress/settings/option/rate.rs
- src/bin/cql-stress-cassandra-stress/settings/option/schema.rs
- Cosmetic changes in the settings module that simplify the access to the parameters (from the main).
- Introduced `operation` module.
- Implemented row-generation logic, based on c-s logic.
- Implemented write and read operations.
- Implemented main logic responsible for running the actual runtime scenario.
> c-s runtime: write and read scenarios

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/operation/read.rs
- src/bin/cql-stress-cassandra-stress/operation/write.rs
- src/bin/cql-stress-cassandra-stress/stats.rs
Since the basic runtime routines have already been implemented, we should display some statistics during the benchmark. This PR introduces a `stats` module responsible for collecting and printing formatted statistics.
- Introduced `stats` module with:
- `Stats` structure implementing `cql_stress::sharded_stats::Stats`
- `StatsFactory` structure implementing `cql_stress::sharded_stats::StatsFactory`
- `LatencyCalculator` trait with two implementations - one calculating raw latencies (`end` - `start`), and the other calculating [coordinated-omission-fixed](https://www.scylladb.com/2021/04/22/on-coordinated-omission/) latencies (`end` - `scheduled_start`). This trait is used by `Stats` structure to keep track of the recorded latencies, based on the type of the latency provided by the user …
> c-s: benchmark statistics

- src/bin/cql-stress-cassandra-stress/settings/param/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/multi_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/parser.rs
- src/bin/cql-stress-cassandra-stress/settings/param/simple_param.rs
Before the changes, a lot of common logic (and fields) would be repeated in implementations of `Param` trait. I found it annoying when implementing yet another type of parameters (`DistributionParam` - https://github.com/scylladb/cql-stress/pull/48) to repeat the same boilerplate code.
Simple examples:
- `required`, `prefix`, `satisfied`, `desc` fields used by both `SimpleParam` and `MultiParam`
- getters and setters for the fields in `Param` trait - the exact same implementations for both types of parameters
- common parsing logic - e.g. check if user-provided argument starts with `prefix`.
This PR introduces a new generic type `ParamWrapperImpl<P: Param>` which wraps the `Param` implementations. The logic shared between all of the types of parameters is extracted to the wrapping type.
- …
> c-s: params wrapper

- src/bin/cql-stress-cassandra-stress/java_generate/distribution/fixed.rs
- src/bin/cql-stress-cassandra-stress/java_generate/distribution/mod.rs
- src/bin/cql-stress-cassandra-stress/java_generate/distribution/sequence.rs
- src/bin/cql-stress-cassandra-stress/java_generate/distribution/uniform.rs
- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/operation/row_generator.rs
- src/bin/cql-stress-cassandra-stress/operation/write.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/column.rs
- src/bin/cql-stress-cassandra-stress/settings/option/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/population.rs
- src/bin/cql-stress-cassandra-stress/settings/option/schema.rs
- src/bin/cql-stress-cassandra-stress/settings/param/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/multi_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/parser.rs
- src/bin/cql-stress-cassandra-stress/settings/param/simple_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
- Refactored the `Param` trait, by extracting most of the common logic to the wrapping type
- introduced `DistributionParam`
- implemented parsing logic for `-col` option
- implemented parsing logic for `-pop` option
> c-s CLI: columns and population options

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/schema.rs
- src/bin/cql-stress-cassandra-stress/settings/param/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
- src/bin/cql-stress-cassandra-stress/settings/test.rs
During the tests of cql-stress with [SCT](https://github.com/scylladb/scylla-cluster-tests), we noticed that there are some minor bugs in parsing logic, which result in runtime errors. Before this PR, there were two issues:
- cql-stress converts all CLI arguments to lowercase. Even though c-s is case-insensitive in most of the cases, there are some arguments that cannot be converted to lowercase - them being replication and compaction strategies which. These strings are directly passed to CQL query, which is sent to Scylla. So, let's say that user specifies `replication(strategy=SimpleStrategy)`. `SimpleStrategy` is then being converted to `simplestrategy` and sent in CQL query. This results in runtime DB error (unknown replication strategy/class).
- minor issue with …
> c-s CLI fixups

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/operation/counter_write.rs
- src/bin/cql-stress-cassandra-stress/operation/mod.rs
- src/bin/cql-stress-cassandra-stress/operation/read.rs
- src/bin/cql-stress-cassandra-stress/operation/row_generator.rs
- src/bin/cql-stress-cassandra-stress/operation/write.rs
- src/bin/cql-stress-cassandra-stress/settings/command/common.rs
- src/bin/cql-stress-cassandra-stress/settings/command/counter.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/multi_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/simple_param.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
- src/configuration.rs
Implemented runtime for both `counter_read` and `counter_write` commands.
This includes:
- renaming `ReadWriteParams` to `CommonParams`
- parsing additional parameter for `counter_write` command (`add=`)
- making `ReadOperation` generic over `RowValidator` trait, since `counter_read` differs from `read` only with validation logic
- implemented `CounterWriteOperation`
- implemented `CounterReadOperation` (as `ReadOperation<ExistsRowValidator>`)
> c-s: counters

- src/bin/cql-stress-cassandra-stress/settings/option/column.rs
- src/bin/cql-stress-cassandra-stress/settings/option/node.rs
- src/bin/cql-stress-cassandra-stress/settings/option/population.rs
- src/bin/cql-stress-cassandra-stress/settings/option/rate.rs
- src/bin/cql-stress-cassandra-stress/settings/option/schema.rs
New rust version expects us to explicitly specify the lifetime of const string variables. Right now, it only generates warnings which result in clippy errors during CI.
See:
```
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #115010 <https://github.com/rust-lang/rust/issues/115010>
```
> c-s options: fix compiler warnings

- src/bin/cql-stress-cassandra-stress/main.rs
By default, cassandra-stress takes 9 attempts to perform an operation before ending the benchmark with failure.
Before this PR, cql-stress would fail immediately after first failed operation. This resulted in SCT run failures (SCT + cql-stress) when some nemesis would kill one of the nodes in the cluster:
```
7689156,   32227,     0.9,     0.8,     1.6,     2.1,     4.7,     9.0,  256.0,      0
7720832,   31675,     0.9,     0.9,     1.6,     2.1,     3.6,     7.3,  257.0,      0
7753593,   32738,     0.9,     0.8,     1.5,     2.0,     3.9,     7.3,  258.0,      0
[2m2023-12-15T15:22:44.866516Z[0m [31mERROR[0m [2mcql_stress_cassandra_stress::operation::read[0m[2m:[0m read error [3merror[0m[2m=[0mInvalid message: Frame error: early eof [3mpartition_key[0m[2m=[0mBlob([80, …
```
> main: set max_retries_per_op to 9 (c-s default)

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-scylla-bench/main.rs
> tracing: disable ansi colors

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/operation/counter_write.rs
- src/bin/cql-stress-cassandra-stress/operation/mod.rs
- src/bin/cql-stress-cassandra-stress/operation/read.rs
- src/bin/cql-stress-cassandra-stress/operation/write.rs
Fixes: https://github.com/scylladb/cql-stress/issues/67
Currently, the common logic for operations is repeated. The idea is to introduce an additional struct that will handle the common logic and encapsulate the logic of specific c-s operation.
This will also help to implement `mixed` operation. This is why, we should merge it before https://github.com/scylladb/cql-stress/pull/63.
Introduced a `CassandraStressOperation` trait which represents a specific c-s operation.
The `GenericCassandraStressOperation` structure will handle the common logic and delegate
the specific operation logic to some object implementing `CassandraStressOperation`.
The common logic that was extracted to `GenericCassandraStressOperation`:
- checks whether `operation_id` > `max_operations`. If true, the stress test …
> c-s operation: Extract common operation logic

- src/bin/cql-stress-cassandra-stress/java_generate/distribution/enumerated.rs
- src/bin/cql-stress-cassandra-stress/java_generate/distribution/mod.rs
- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/operation/mixed.rs
- src/bin/cql-stress-cassandra-stress/operation/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/common.rs
- src/bin/cql-stress-cassandra-stress/settings/command/counter.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mixed.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
Cassandra-stress supports mixed workloads. It allows to run multiple kinds of operations. Allowed operations are:
- read
- write
- counter_read
- counter_write
The parameters supported by `mixed` command are:
- all of the common parameters (e.g. used by `read`)
- all of the `counter_write` parameters
- `ratio()` parameter based on which tool samples an operation to execute. E.g. `ratio(read=2, write=1)` means that there will be approximately 2 read operations per 1 write operation.
- `clustering` distribution parameter which tells the tool how many times to run the operation that just got sampled.
- Prepared `settings` module for `MixedOperation`
- Implemented `MixedOperation`
> c-s mixed operation

- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-cassandra-stress/java_generate/values/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/common.rs
- src/bin/cql-stress-scylla-bench/args.rs
- src/bin/cql-stress-scylla-bench/operation/read.rs
Bumped driver's version to most recent `0.12.0`.
Some code needed to be adjusted:
`Consistency` enum supports two new variants: `Serial` and `LocalSerial`. Updated `show_consistency_level` accordingly.
`Murmur3Partitioner`'s API changed a bit, so its usage is adjusted in `GeneratorConfig::new`
`SerializedValues` was renamed to `LegacySerializedValues` in serialization API refactor.
I changed the usage of `SerializedValues` simply to `Vec<i64>` in s-b's `ReadOperation`. I used `Vec<i64>` since both `partition_key` and `clustering_key`s are `bigint`s.
Maybe it's better use `LegacySerializedValues`, but I'm not quite sure as I'm not familiar with the changes introduced in 0.11.0.
> Bump driver version to 0.12.0

- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/option/column.rs
Fixes: https://github.com/scylladb/cql-stress/issues/73
cassandra-stress supports a distribution syntax for `-col n=` parameter. However, it only allows the `FIXED(?)` distribution for cql mode.
Before this commit, cql-stress would accept a u64 value for the value of this parameter.
To make our CLI compatible with c-s (so it can be easily replaced in SCT), we will accept `FIXED(<u64>)` syntax as well.
> c-s/col: c-s compatibility for -col n= parameter

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/settings/command/common.rs
- src/bin/cql-stress-cassandra-stress/settings/command/counter.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mixed.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/empty_queries_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/full_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/minimal_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/missing_keyspace_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/unknown_field_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/unknown_query_field_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/user.rs
- src/bin/cql-stress-cassandra-stress/settings/param/parser.rs
ref: https://cassandra.apache.org/doc/stable/cassandra/tools/cassandra_stress.html#user-mode
User command is the most complex c-s command. It is very flexible and allows user to define his own schema, as well as stress queries. We obviously want to support this command in cql-stress.
ref: https://cassandra.apache.org/doc/stable/cassandra/tools/cassandra_stress.html#profile
User can define the benchmark via profile yaml file. In this PR we introduce support for most commonly used profile parameters, which are:
- `keyspace`
- `keyspace_definition`
- `table`
- `table_definition`
- `queries`
- Introduced `UserParams` struct which contains the payload needed to run the benchmark
- Implemented CLI parsing logic for `user` command, which includes the `profile=` parameter that specifies the path …
> User command: parsing logic + schema creation

- src/bin/cql-stress-scylla-bench/distribution.rs
As of now, the get_f64 method of `Distribution` trait is unused. However, it will be used once the generators for float types are implemented.
Let's mark it with `#[allow(dead_code)]` until that happens to suppress clippy errors.
> Fix clippy errors

- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-cassandra-stress/java_generate/values/mod.rs
The only API breaking change affecting the tool is that `Token`'s salt field is private and exposed via public getter.
> cargo: bump driver version to 0.13

- src/bin/cql-stress-cassandra-stress/operation/mod.rs
- src/bin/cql-stress-cassandra-stress/operation/user.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/full_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/user.rs
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
- tools/util/cassandra_stress.py
Fix: https://github.com/scylladb/cql-stress/issues/80
This PR extends a CLI for user command by `ops()` and `clustering=` parameters.
The semantics of parameters:
- `ops` -> defines a ratio with which the operation/queries will be
sampled. For example `ops(foo=1,bar=2)` means that the tool will
approximately execute 2 `bar` queries per 1 `foo` query. These queries
must be defined in the profile yaml.
- `clustering` -> a distribution. The tool will sample a value from
this distribution to decide how many times to execute
current operation/query (which was sampled based on `ops`). The value
will be treated as a counter. When counter reaches 0, new operation
is sampled, and so, the new value of counter is sampled as well.
The struct that will make use of these parameters is …
> c-s: Implement query/operation sampler

- src/bin/cql-stress-scylla-bench/gocompat/strconv.rs
- src/bin/cql-stress-scylla-bench/main.rs
- src/bin/cql-stress-scylla-bench/operation/scan.rs
- src/bin/cql-stress-scylla-bench/workload/timeseries_read.rs
- src/bin/cql-stress-scylla-bench/workload/timeseries_write.rs
There were two issues clippy was complaining about:
- use of legacy numeric types (i.e. `std::{u32. u64}`)
- unused field in `Timeseries{Read/Write}Config` structs (no idea why this wasn't recognized before)
This PR fixes these issues.
> CI: fix clippy issues

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
fix: https://github.com/scylladb/cql-stress/issues/85
List of tables created for each command:
- read/write -> `keyspace1.standard1` table
- counter_read/counter_write -> `keyspace1.counter1` table
- mixed -> both `keyspace1.[standard1/counter1]` tables
- user -> keyspace and table provided in user profile yaml file
> c-s: create correct tables based on workload

- src/bin/cql-stress-cassandra-stress/java_generate/distribution/enumerated.rs
- src/bin/cql-stress-cassandra-stress/operation/mixed.rs
See the discussion: https://github.com/scylladb/cql-stress/pull/86#issuecomment-2204524664.
My last PR (https://github.com/scylladb/cql-stress/pull/86) introduced a new bug - `mixed` command tries to prepare a statement for each operation (read/write/counter_read/counter_write), even though it does not create the tables.
This PR fixes it so we prepare the statements only for the operations that are going to be sampled (were specified in `ratio()` parameter by the user). We obviously then assume that the corresponding write workload was ran beforehand and that it created tables used by the `mixed` workload.
> mixed: prepare statements only for subcommands defined by user

- src/bin/cql-stress-cassandra-stress/java_generate/values/mod.rs
- src/bin/cql-stress-cassandra-stress/operation/row_generator.rs
Clippy (1.81.0) is complaining about indendation issues for docstring statements following a list. The list, and the following statement should be separated by an empty line.
> clippy: fix indentation issues in docstring

- tools/util/cassandra_stress.py
Packages for 3.11.16 were already removed, we need to bump the version to 3.11.17.
> ci: bump cassandra version to 3.11.17

- README.md
- src/bin/cql-stress-cassandra-stress/operation/user.rs
- src/bin/cql-stress-cassandra-stress/settings/command/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/command/test_user_profile_yamls/insert_query_profile.yaml
- src/bin/cql-stress-cassandra-stress/settings/command/user.rs
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
Fix: https://github.com/scylladb/cql-stress/issues/91
This PR introduces a logic for predefined `insert` operation.
Changes:
- adjusted CLI to support `insert` operation for `user` command. Users can now choose to perform this operation (with a given sample ratio weight) via `ops()` parameter.
- implemented runtime logic for `insert` operation. As the name suggests, the operation simply generates a row and inserts it to database.
- updated README
- TODO: implement runtime tests in python
> c-s: Implement `insert` operation for user profiles

- Cargo.lock
- Cargo.toml
- src/bin/cql-stress-cassandra-stress/operation/counter_write.rs
- src/bin/cql-stress-cassandra-stress/operation/read.rs
- src/bin/cql-stress-cassandra-stress/operation/user.rs
- src/bin/cql-stress-cassandra-stress/operation/write.rs
- src/bin/cql-stress-cassandra-stress/settings/command/user.rs
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-scylla-bench/main.rs
- src/bin/cql-stress-scylla-bench/operation/counter_update.rs
- src/bin/cql-stress-scylla-bench/operation/write.rs
- src/lib.rs
The only API breaking changes that needed to be addressed were rust driver's changes regarding query/execute API changes regarding paging.
We changed `query/execute` calls to `[query/execute]_unpaged` calls, adding the comments explaining why it makes sense to make use of unpaged queries in these places (unless it is obvious).
> cargo: bump rust-driver version to 0.14

- src/bin/cql-stress-cassandra-stress/hdr_logger.rs
- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/operation/counter_write.rs
- src/bin/cql-stress-cassandra-stress/operation/mixed.rs
- src/bin/cql-stress-cassandra-stress/operation/mod.rs
- src/bin/cql-stress-cassandra-stress/operation/read.rs
- src/bin/cql-stress-cassandra-stress/operation/user.rs
- src/bin/cql-stress-cassandra-stress/operation/write.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/log.rs
- src/bin/cql-stress-cassandra-stress/settings/option/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
- src/bin/cql-stress-cassandra-stress/stats.rs
- tools/cql-stress-cassandra-stress-ci.py
- tools/test_hdr_logging.py
- tools/util/cassandra_stress.py
Introduced hdr histogram file logger supporting different types of statement (read, write, couter_read, counter_write). Also handling `-log interval` for proper granularity.
closes: https://github.com/scylladb/cql-stress/issues/103
> feature(hdrh_logger): added hdr histograms logger

- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/option/rate.rs
Seems `-rate` fixed option changed in c-s and this code reflects that change:
if `fixed=op/s` is set, it enables `co_fixed` flag and when `throttle=op/s` is used `co_fixed` flag is `false`
fixes: https://github.com/scylladb/cql-stress/issues/108
> fix(rate): adjusted -rate option to match c-s

- src/bin/cql-stress-cassandra-stress/main.rs
- src/bin/cql-stress-cassandra-stress/settings/cs_args_bad_test.in
- src/bin/cql-stress-cassandra-stress/settings/cs_args_good_test.in
- src/bin/cql-stress-cassandra-stress/settings/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/mod.rs
- src/bin/cql-stress-cassandra-stress/settings/option/transport.rs
- src/bin/cql-stress-cassandra-stress/settings/param/types.rs
Introducing basic `-transport` support to cassandra-stress frontend.
closes: https://github.com/scylladb/cql-stress/issues/136
> feature(c-s): add -transport option support

- Cargo.lock
- Cargo.toml
- src/configuration.rs
- src/run.rs
`tokio::sleep_until` operates on millisecond granularity. In result, if the sleep time is <1ms, we may sleep longer than expected.
Fix by using `tokio_timerfd` lib for precision sleep.
fixes: https://github.com/scylladb/cql-stress/issues/134
> fix: fix latency precision for fixed rate
